service: serverless-auth-service

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  memorySize: 512

functions:
  api:
    handler: src/api.handler
    events:
      - http:
          path: /
          method: ANY
          # cors: true
          # private: true
      - http:
          path: /{any+}
          method: ANY
          # cors: true
          # private: true