service: galerie
frameworkVersion: '3'

package:
  exclude:
    - node_modules/**
    - .serverless/**

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true
  esbuild:
    config: './esbuild.config.js'
  envs:
    dev:
      G_FILE_STORAGE_TYPE: "s3"

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  stage: dev
  memorySize: 1024

functions:
  api:
    handler: ./src/api/api-lambda.handler
    events:
      - httpApi: '*'
    environment: ${self:custom.envs.${sls:stage}}