name: Deploy dev environment
on:
  push:
    tags:
      - dev-*

jobs:
  deploy-dev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Deploy serverless backend
        uses: ./.github/actions/deploy-serverless-backend
        with:
          stage: dev
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy website
        uses: ./.github/actions/deploy-website
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          static-bucket-name: ${{ secrets.STATIC_BUCKET_NAME }}
