name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Prettier
        run: pnpm prettier
  tsc:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: npx tsc
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Tests
        run: pnpm test
